#!/bin/sh
echo -n "파일/디렉토리 이름 입력 [enter] "
read filename

if [ ! -e "$filename" ] && [ ! -L "$filename" ]; then
    echo "$filename 은 존재하지 않습니다."
else
    if [ -L "$filename" ]; then
        type="심볼릭링크"
    elif [ -d "$filename" ]; then
        type="디렉토리"
    elif [ -b "$filename" ]; then
        type="블록장치"
    elif [ -c "$filename" ]; then
        type="문자장치"
    elif [ -p "$filename" ]; then
        type="파이프"
    elif [ -S "$filename" ]; then
        type="소켓"
    elif [ -f "$filename" ]; then
        type="보통파일"
    fi
    echo "$filename 은 ${type} 입니다."
fi
